server: 
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: 
    password: 
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
        
  application:
    name: USER-MICROSERVICE
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
       