server: 
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: 
    password: 
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
        
  application:
    name: USER-MICROSERVICE

  config:
    import:
    - configserver:http://localhost:8085
  profiles:
    active:
    - prod
    

    
 
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
  retry: 
    instances: 
      ratingRetry:
        max-attempts: 3
        wait-duration: 5s
       
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      